module.exports = [
  {
    title: "Magasin",
    fields: [
      { key: "nom", label: "Nom du magasin" },
      { key: "rue", label: "Rue / repère" },
      { key: "anciennete", label: "Ancienneté" },
      { key: "employes", label: "Personnes qui travaillent" },
      { key: "type", label: "Type de magasin" },
      { key: "type_autre", label: "Type (précision)" },
      { key: "surface", label: "Surface" },
    ],
  },
  {
    title: "Ce qui se vend",
    fields: [
      { key: "familles", label: "Familles vendues" },
      { key: "top1", label: "Famille n°1 (chiffre d'affaires)" },
      { key: "top2", label: "Famille n°2" },
      { key: "top3", label: "Famille n°3" },
      { key: "manquant", label: "Demandé souvent mais absent ou en retard" },
      { key: "voitures", label: "Marques les plus demandées" },
      { key: "voitures_autres", label: "Autres marques" },
      { key: "qualite", label: "Qualité vendue" },
      { key: "pct_adaptable", label: "Part adaptable", format: "pct" },
      { key: "pct_origine", label: "Part origine", format: "pct" },
    ],
  },
  {
    title: "Clients",
    fields: [
      { key: "acheteurs", label: "Qui achète" },
      { key: "pct_garages", label: "Part des garages", format: "pct" },
      { key: "panier", label: "Panier typique" },
      { key: "clients_jour", label: "Clients par jour" },
      { key: "heures_fortes", label: "Jours / heures forts" },
      { key: "compare_prix", label: "Le client compare les prix" },
      { key: "critere1", label: "Critère n°1 du client" },
      { key: "critere2", label: "Critère n°2 du client" },
      { key: "critere3", label: "Critère n°3 du client" },
    ],
  },
  {
    title: "Prix",
    fields: [
      { key: "p1_nom", label: "Pièce 1" },
      { key: "p1_qualite", label: "Pièce 1 — qualité" },
      { key: "p1_achat", label: "Pièce 1 — prix d'achat", format: "mad" },
      { key: "p1_vente", label: "Pièce 1 — prix de vente client", format: "mad" },
      { key: "p1_vente_garage", label: "Pièce 1 — prix garage", format: "mad" },
      { key: "p2_nom", label: "Pièce 2" },
      { key: "p2_qualite", label: "Pièce 2 — qualité" },
      { key: "p2_achat", label: "Pièce 2 — prix d'achat", format: "mad" },
      { key: "p2_vente", label: "Pièce 2 — prix de vente client", format: "mad" },
      { key: "p2_vente_garage", label: "Pièce 2 — prix garage", format: "mad" },
      { key: "p3_nom", label: "Pièce 3 (optionnel)" },
      { key: "p3_achat", label: "Pièce 3 — prix d'achat", format: "mad" },
      { key: "p3_vente", label: "Pièce 3 — prix de vente", format: "mad" },
      { key: "nego", label: "Façon de vendre" },
      { key: "rabais_pct", label: "Rabais habituel pour un garage fidèle", format: "pct" },
      { key: "seuil_prix", label: "Écart de prix pour changer de fournisseur" },
      { key: "prix_max", label: "Prix d'achat maximum accepté (pièce 1)", format: "mad" },
      { key: "prix_doute", label: "Prix en dessous duquel la qualité est douteuse (pièce 1)", format: "mad" },
      { key: "credit", label: "Vente à crédit aux garages" },
      { key: "credit_jours", label: "Délai de crédit (jours)" },
      { key: "credit_pct", label: "Part des ventes à crédit", format: "pct" },
    ],
  },
  {
    title: "Fournisseurs",
    fields: [
      { key: "sources", label: "Où le magasin achète" },
      { key: "source_grossiste", label: "Grossiste (précision)" },
      { key: "source_autre", label: "Autre source" },
      { key: "nb_fournisseurs", label: "Nombre de fournisseurs fixes" },
      { key: "fournisseur_principal", label: "Fournisseur principal (type)" },
      { key: "frequence_stock", label: "Réassorts par mois" },
      { key: "reassort", label: "Montant d'un réassort" },
      { key: "achat_mois", label: "Achats du mois (estimation)", format: "mad" },
      { key: "delai", label: "Délai de livraison habituel" },
      { key: "probleme", label: "Problème n°1 avec les fournisseurs" },
      { key: "retours", label: "Retour des pièces défectueuses" },
      { key: "tester", label: "Prêt à tester un nouveau fournisseur" },
      { key: "test_montant", label: "Montant du premier test", format: "mad" },
    ],
  },
  {
    title: "Quartier",
    fields: [
      { key: "nb_magasins", label: "Nombre de magasins pièces auto dans le quartier" },
      { key: "concurrent", label: "Concurrent direct" },
      { key: "avantage", label: "Pourquoi le client vient ici" },
      { key: "manque", label: "Ce qui manque au magasin" },
      { key: "demande", label: "Demande cette année" },
      { key: "demande_pourquoi", label: "Pourquoi la demande change" },
      { key: "attente", label: "Ce qu'un fournisseur local doit faire pour travailler avec eux" },
      { key: "rappel", label: "Accepte d'être recontacté" },
      { key: "telephone", label: "Téléphone" },
    ],
  },
];
